### ISSUE TITLE
Event listener not detached on component destruction.

### ISSUE THREAD

**Issue by behlers** [FranzSkuffka/vue-medium-editor#24]
I have a problem with destroying a component with a medium editor component, and using vuex.
I have tried to build an example in jsfiddle but i could not find a current vue medium editor cdn:
https://jsfiddle.net/bsyq7nuf/3/
And jsfiddle would not work with my compiled app.js file.
The Problem is the "DOMSubtreeModified eventlistener" which calls the edit event, even, when the element gets destroyed.
I kind of fixed it like this: 
I added a bool, set it to true in the beforeDestroy method and checked if it is true:
`if (this.$refs.element.childNodes[0] && !this.amDestroyen) {`
I am not sure if that is the right way to fix the problem.

**Comment by janwirth** [comment]
Actually, this should be solved when using the built-in event listener of the editor.
The CDN links are available here.
https://franzskuffka.github.io/vue-medium-editor/
A codepen would be very helpful.

By the way, you can use backticks \` to format `code`!

**Comment by behlers** [comment]
Hi there. Thank you for the cdn, but that seams to be the same old version without this part 

```
watch: {
    text() {
      if (this.text === this.$refs.element.innerHTML) {
        // if the change is done by this same component, do not update the contents to prevent
        // caret from resetting to the beginning of the editor
        return;
      }
      this.$refs.element.innerHTML = this.text
    }
  }
```

I build the same thing again in Codepen: https://codepen.io/anon/pen/evQoMp where you can see that the first dump and the second interface are not in sync.

**Comment by janwirth** [comment]
Use three backticks \`\`\` to wrap
```
a block of code :D
```

I will investigate soon, maybe @okneloper has an idea how to help :)

**Comment by pizzot** [comment]
@behlers how do you manage to change the content of the item that you had deleted?

Does using `Vue.delete()` instead of `filter()` help?:
```
DEL_ITEM(state, index) {
      Vue.delete(state.items, index);
},
```

**Comment by behlers** [comment]
@okneloper thank you for the tip, but that did not work.
Still the same, the content of the element is gone but the element itself is still there.

**Comment by pizzot** [comment]
@behlers I am not sure I understand the issue then. Your fiddle does not work either. Can fix the fiddle and add steps to reproduce the issue?

**Comment by behlers** [comment]
@okneloper thank you for your patience, here is the page i am working on and here the problem should be apparent: http://laborator.tappr.de/template

**Comment by pizzot** [comment]
@behlers can you attach the source also?

**Comment by janwirth** [comment]
Guys, I have a rough idea on what should be done. I will implement this, close the other issue as well & release a version. Once this is done I will update this issue so @behlers can test it for him.

**Comment by janwirth** [comment]
So we should refer to the following section during binding and destruction:
https://github.com/yabwe/medium-editor#capturing-dom-changes
Also subscribing / unsubscribing must respect the multiple / single instance option added by @okneloper.

**Comment by pizzot** [comment]
@FranzSkuffka multiple / single instance is not something I had added, but I have noticed some weird behaviour today when working with serveral editors.
